// 4-topshiriq!!!
let sonlar = 10;
random = Math.random() * sonlar + 1
ranglar = parseInt(random)
// console.log(ranglar)
switch (ranglar) {
    case 1: {
        console.log("red")
        break;
    }
    case 2: {
        console.log("blue")
        break;
    }
    case 3: {
        console.log("green")
        break;
    }
    case 4: {
        console.log("black")
        break;
    }
    case 5: {
        console.log("white")
        break;
    }
    case 6: {
        console.log("yellow")
        break;
    }
    case 7: {
        console.log("grey")
        break;
    }
    case 8: {
        console.log("pink")
        break;
    }
    case 9: {
        console.log("lime")
        break;
    }
    case 10: {
        console.log("aqua")
        break;
    }
}